name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # الخطوة الجديدة: توليد google-services.json من السر
      - name: Set up google-services.json
        run: bash scripts/setup-google-services.sh
        env:
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build (assemble + unit tests) with diagnostics
        run: |
          ./gradlew --stop
          ./gradlew clean assembleDebug test --stacktrace --info --no-daemon

      - name: Android Lint (debug)
        run: ./gradlew lintDebug --stacktrace --no-daemon

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            **/build/reports/**
            **/build/test-results/**
            **/outputs/**

      - name: Upload Gradle logs (kapt, stubs, classes)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: |
            **/build/tmp/kapt*/stubs/**
            **/build/tmp/kapt3/classes/**
            **/build/tmp/kapt3/incApCache/**
            **/build/tmp/kapt3/**/kaptGenerateStubs*/kapt.log

      - name: Upload app build directory (summary)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: app/build/
          if-no-files-found: warn
